apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-storage
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  mountOptions:
    - nfsvers=3
  nfs:
    server: 10.0.2.4
    path: /arr-fs