apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-storage
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/media
    type: DirectoryOrCreate
