apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
  namespace: media
spec:
  storageClassName: manual
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
